;;; genetics-test-util.el --- shared helpers for genetics tests -*- lexical-binding: t; -*-

;;; Commentary:

;; Fixture lookup, temp cache directories and small file writers.  Tests
;; only ever read files under test/fixtures or temp files they create.

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'genetics)

(defconst genetics-test--dir
  (file-name-directory (or load-file-name buffer-file-name))
  "Directory containing the tests.")

(defun genetics-test-fixture (name)
  "Return the absolute path of fixture NAME."
  (expand-file-name (concat "fixtures/" name) genetics-test--dir))

(defun genetics-test-root ()
  "Return the repository root directory."
  (file-name-directory (directory-file-name genetics-test--dir)))

(defmacro genetics-test-with-env (&rest body)
  "Run BODY with a temp cache directory, no loaded kits and no buffers leaked."
  (declare (indent 0))
  `(let* ((genetics-cache-directory (file-name-as-directory
                                     (make-temp-file "genetics-test-cache" t)))
          (genetics-use-cache nil)
          (genetics-loaded-kits nil)
          (genetics-snpedia-enabled nil)
          (genetics-snpedia-confirmed nil)
          (genetics--annotation-cache nil))
     (unwind-protect (progn ,@body)
       (delete-directory genetics-cache-directory t)
       (dolist (b (buffer-list))
         (when (string-prefix-p "*genetics" (buffer-name b))
           (kill-buffer b))))))

(defun genetics-test-load (name &rest args)
  "Parse fixture NAME with ARGS and register the kit."
  (let ((kit (apply #'genetics-parse-file (genetics-test-fixture name) args)))
    (setf (genetics-kit-name kit) (genetics--unique-name (genetics-kit-name kit)))
    (genetics-register-kit kit)))

(defun genetics-test-write-23andme (rows &optional build-line)
  "Write ROWS ((RSID CHROM POS GT) ...) as a 23andMe file; return its path.
BUILD-LINE replaces the default build comment."
  (let ((file (make-temp-file "genetics-test-" nil ".txt")))
    (with-temp-file file
      (insert "# This data file generated by 23andMe at: Sat Jan 03 2026\n"
              (or build-line "# We are using reference human assembly build 37 (also known as Annotation Release 104).\n")
              "# rsid\tchromosome\tposition\tgenotype\n")
      (dolist (r rows)
        (insert (format "%s\t%s\t%s\t%s\n" (nth 0 r) (nth 1 r) (nth 2 r) (nth 3 r)))))
    file))

(defun genetics-test-kit-from-rows (rows &optional build-line)
  "Return a registered kit built from ROWS (see `genetics-test-write-23andme')."
  (let* ((file (genetics-test-write-23andme rows build-line))
         (kit (genetics-parse-file file)))
    (delete-file file)
    (setf (genetics-kit-name kit) (genetics--unique-name (genetics-kit-name kit)))
    (genetics-register-kit kit)))

(defun genetics-test-gzip (src)
  "Return the path of a gzip copy of file SRC (temp file)."
  (let ((out (make-temp-file "genetics-test-" nil ".vcf.gz")))
    (should (eq 0 (call-process "gzip" nil (list :file out) nil "-c" src)))
    out))

(defun genetics-test-snps (kit)
  "Return the SNPs of eager KIT sorted by rsid, for `equal' comparisons."
  (let (acc)
    (maphash (lambda (_k v) (push v acc)) (genetics-kit-table kit))
    (sort acc (lambda (a b) (string< (genetics-snp-rsid a) (genetics-snp-rsid b))))))

(defun genetics-test-buffer-text (name)
  "Return the text of the buffer called NAME."
  (with-current-buffer name (buffer-substring-no-properties (point-min) (point-max))))

(provide 'genetics-test-util)
;;; genetics-test-util.el ends here
